DATA LIST FILE='C:\COUNTRIES\CD61\CDPR61FL.DAT' RECORDS=1
  /
  HHID        1-12   (A)
  HVIDX      13-14  
  HV000      15-17   (A)
  HV001      18-25  
  HV002      26-29  
  HV003      30-32  
  HV004      33-36  
  HV005      37-44  
  HV006      45-46  
  HV007      47-50  
  HV008      51-54  
  HV009      55-56  
  HV010      57-58  
  HV011      59-60  
  HV012      61-62  
  HV013      63-64  
  HV014      65-66  
  HV015      67-67  
  HV016      68-69  
  HV017      70-70  
  HV018      71-73  
  HV019      74-75  
  HV020      76-76  
  HV021      77-80  
  HV022      81-84  
  HV023      85-86  
  HV024      87-88  
  HV025      89-89  
  HV026      90-90  
  HV027      91-91  
  HV028      92-99  
  HV030     100-102 
  HV031     103-105 
  HV032     106-107 
  HV035     108-109 
  HV040     110-113 
  HV041     114-115 
  HV042     116-116 
  HV044     117-117 
  HV201     118-119 
  HV202     120-121 
  HV204     122-124 
  HV205     125-126 
  HV206     127-127 
  HV207     128-128 
  HV208     129-129 
  HV209     130-130 
  HV210     131-131 
  HV211     132-132 
  HV212     133-133 
  HV213     134-135 
  HV214     136-137 
  HV215     138-139 
  HV216     140-141 
  HV217     142-142 
  HV218     143-144 
  HV219     145-145 
  HV220     146-147 
  HV221     148-148 
  HV225     149-149 
  HV226     150-151 
  HV227     152-152 
  HV228     153-153 
  HV230A    154-154 
  HV230B    155-155 
  HV232     156-156 
  HV232B    157-157 
  HV232C    158-158 
  HV232D    159-159 
  HV232E    160-160 
  HV232Y    161-161 
  HV234     162-164 
  HV234A    165-165 
  HV235     166-166 
  HV236     167-167 
  HV237     168-168 
  HV237A    169-169 
  HV237B    170-170 
  HV237C    171-171 
  HV237D    172-172 
  HV237E    173-173 
  HV237F    174-174 
  HV237G    175-175 
  HV237H    176-176 
  HV237I    177-177 
  HV237J    178-178 
  HV237K    179-179 
  HV237X    180-180 
  HV237Z    181-181 
  HV238     182-183 
  HV239     184-184 
  HV240     185-185 
  HV241     186-186 
  HV242     187-187 
  HV243A    188-188 
  HV243B    189-189 
  HV243C    190-190 
  HV243D    191-191 
  HV244     192-192 
  HV245     193-195 
  HV246     196-196 
  HV246A    197-198 
  HV246B    199-200 
  HV246C    201-202 
  HV246D    203-204 
  HV246E    205-206 
  HV246F    207-208 
  HV246G    209-210 
  HV246H    211-212 
  HV246I    213-214 
  HV246J    215-216 
  HV246K    217-218 
  HV247     219-219 
  HV252     220-220 
  HV253     221-221 
  HV253A    222-222 
  HV253B    223-223 
  HV253C    224-224 
  HV253D    225-225 
  HV253E    226-226 
  HV253F    227-227 
  HV253G    228-228 
  HV253H    229-229 
  HV253X    230-230 
  HV253Z    231-231 
  HV270     232-232 
  HV271     233-240 
  HML1      241-242 
  HML1A     243-243 
  HML2      244-245 
  CHL0      246-247 
  SHPOOL    248-249 
  SHNPROVIN  250-251 
  SH110F    252-252 
  SH110G    253-253 
  SH110H    254-254 
  SH110I    255-255 
  SH110J    256-256 
  SH110K    257-257 
  SH110L    258-258 
  SH110M    259-259 
  SH118H    260-260 
  SH118I    261-261 
  SH118J    262-262 
  SH136AA   263-263 
  SH136AB   264-264 
  SH136AC   265-265 
  SH136AD   266-266 
  SH136AE   267-267 
  SH136AF   268-268 
  SH136AX   269-269 
  SH136AZ   270-270 
  SH136BA   271-271 
  SH136BB   272-272 
  SH136BC   273-273 
  SH136BD   274-274 
  SH136BE   275-275 
  SH136BF   276-276 
  SH136BG   277-277 
  SH136BX   278-278 
  SH136BZ   279-279 
  SH136CA   280-280 
  SH136CB   281-281 
  SH136CC   282-282 
  SH136CD   283-283 
  SH136CE   284-284 
  SH136CF   285-285 
  SH136CG   286-286 
  SH136CX   287-287 
  SH242     288-292 
  SH252A    293-293 
  SH252B    294-295 
  SH252C    296-297 
  SH256A    298-298 
  SH256B    299-299 
  SH256C    300-300 
  SH256D    301-301 
  SH258     302-303 
  SH259     304-304 
  SH260     305-305 
  SH261A    306-306 
  SH261B    307-307 
  SH261C    308-308 
  SH261D    309-309 
  SH261E    310-310 
  SH261F    311-311 
  SH262     312-312 
  SH263     313-314 
  SH264A    315-315 
  SH264B    316-316 
  SH264C    317-317 
  SH264D    318-318 
  SH264E    319-319 
  SH264F    320-320 
  SH264G    321-321 
  SH266     322-323 
  SH271     324-325 
  SH272A    326-326 
  SH272B    327-327 
  SH272C    328-328 
  SH272D    329-329 
  SH272E    330-330 
  SH272F    331-331 
  SH272G    332-332 
  SH272H    333-333 
  SH272I    334-334 
  SH272J    335-335 
  SH272K    336-336 
  SH273     337-337 
  HV101     338-339 
  HV102     340-340 
  HV103     341-341 
  HV104     342-342 
  HV105     343-344 
  HV106     345-345 
  HV107     346-347 
  HV108     348-349 
  HV109     350-350 
  HV110     351-351 
  HV111     352-352 
  HV112     353-354 
  HV113     355-355 
  HV114     356-357 
  HV115     358-358 
  HV116     359-359 
  HV117     360-360 
  HV118     361-361 
  HV120     362-362 
  HV121     363-363 
  HV122     364-364 
  HV123     365-366 
  HV124     367-368 
  HV125     369-369 
  HV126     370-370 
  HV127     371-372 
  HV128     373-374 
  HV129     375-375 
  HV140     376-376 
  IDXH4     377-378 
  SH21      379-379 
  SH22      380-381 
  SH23      382-382 
  SH24      383-384 
  SH276     385-386 
  SH277     387-387 
  SH278     388-389 
  SH279     390-390 
  SH280     391-391 
  SH281     392-392 
  SH282     393-393 
  SH283     394-394 
  SH284     395-395 
  SH285     396-396 
  SH286     397-397 
  SH288     398-398 
  SH289     399-399 
  SH290     400-400 
  SH310A    401-401 
  SH312     402-406  (A)
  SH318A    407-407 
  SH318B    408-408 
  SH318C    409-409 
  SH318D    410-410 
  SH318E    411-411 
  SH318F    412-412 
  SH318G    413-413 
  SH318H    414-414 
  SH318Y    415-415 
  SH322     416-416 
  SH325     417-417 
  SH327     418-418 
  SHROUG    419-419 
  SHOREI    420-420 
  SHRUBE    421-421 
  SHVARI    422-422 
  SHTETA    423-423 
  HA0       424-425 
  HA1       426-427 
  HA2       428-431 
  HA3       432-435 
  HA4       436-439 
  HA5       440-443 
  HA6       444-448 
  HA11      449-452 
  HA12      453-457 
  HA12A     458-462 
  HA12B     463-467 
  HA13      468-468 
  HA32      469-472 
  HA33      473-473 
  HA35      474-475 
  HA40      476-479 
  HA41      480-483 
  HA50      484-484 
  HA51      485-486 
  HA52      487-487 
  HA53      488-490 
  HA54      491-491 
  HA55      492-492 
  HA56      493-495 
  HA57      496-496 
  HA58      497-497 
  HA60      498-498 
  HA61      499-499 
  HA62      500-504  (A)
  HA63      505-505 
  HA64      506-506 
  HA65      507-507 
  HA66      508-508 
  HA67      509-510 
  HA68      511-511 
  HA69      512-519 
  HA70      520-522 
  HC0       523-524 
  HC1       525-526 
  HC2       527-530 
  HC3       531-534 
  HC4       535-538 
  HC5       539-542 
  HC6       543-547 
  HC7       548-551 
  HC8       552-555 
  HC9       556-560 
  HC10      561-564 
  HC11      565-568 
  HC12      569-573 
  HC13      574-574 
  HC15      575-575 
  HC16      576-577 
  HC17      578-579 
  HC18      580-581 
  HC19      582-585 
  HC27      586-586 
  HC30      587-588 
  HC31      589-592 
  HC32      593-596 
  HC33      597-597 
  HC51      598-599 
  HC52      600-600 
  HC53      601-603 
  HC55      604-604 
  HC56      605-607 
  HC57      608-608 
  HC58      609-609 
  HC60      610-612 
  HC61      613-613 
  HC62      614-615 
  HC63      616-618 
  HC64      619-620 
  HC68      621-621 
  HC70      622-625 
  HC71      626-629 
  HC72      630-633 
  HC73      634-637 
  HB0       638-639 
  HB1       640-641 
  HB2       642-645 
  HB3       646-649 
  HB4       650-653 
  HB5       654-657 
  HB6       658-662 
  HB11      663-666 
  HB12      667-671 
  HB12A     672-676 
  HB12B     677-681 
  HB13      682-682 
  HB32      683-686 
  HB33      687-687 
  HB35      688-689 
  HB40      690-693 
  HB41      694-697 
  HB50      698-698 
  HB51      699-700 
  HB52      701-701 
  HB53      702-704 
  HB55      705-705 
  HB56      706-708 
  HB57      709-709 
  HB58      710-710 
  HB60      711-711 
  HB61      712-712 
  HB62      713-717  (A)
  HB63      718-718 
  HB64      719-719 
  HB65      720-720 
  HB66      721-721 
  HB67      722-723 
  HB68      724-724 
  HB69      725-732 
  HB70      733-735 
  HMLIDX    736-737 
  HML3      738-738 
  HML4      739-740 
  HML5      741-741 
  HML6      742-742 
  HML7      743-744 
  HML8      745-745 
  HML9      746-747 
  HML10     748-748 
  HML11     749-749 
  HML21     750-750 
  HMLA      751-752 
  HMLB      753-754 
  HMLC      755-756 
  HMLD      757-758 
  HMLE      759-760 
  HMHIDX    761-762 
  HML12     763-763 
  HML13     764-764 
  HML14     765-765 
  HML15     766-766 
  HML16     767-768 
  HML16A    769-770 
  HML17     771-771 
  HML18     772-772 
  HML19     773-773 
  HML20     774-774 
  HML30     775-776 
  HML31     777-777 
  HML32     778-778 
  HML32A    779-779 
  HML32B    780-780 
  HML32C    781-781 
  HML32D    782-782 
  HML32E    783-783 
  HML32F    784-784 
  HML32G    785-785 
  HML33     786-786 
  HML34     787-791  (A)
  HML35     792-792 
  SHCOL3A   793-794 
  SH203     795-796 
  SH205     797-798 
  SH206     799-799 
  SH207     800-804 
  SH207AA   805-809 
  SH207AB   810-814 
  SH207AC   815-819 
  SH207AD   820-824 
  SH207AE   825-829 
  SH207AF   830-834 
  SH208     835-835 
  SH209     836-837 
  SH210     838-838 
  SH211     839-843 
  SH211AA   844-848 
  SH211AB   849-853 
  SH211AC   854-858 
  SH211AD   859-863 
  SH211AE   864-868 
  SH211AF   869-873 
  SH212     874-874 
  SH213     875-876 
  SH214     877-877 
  SH215     878-882 
  SH215AA   883-887 
  SH215AB   888-892 
  SH215AC   893-897 
  SH215AD   898-902 
  SH215AE   903-907 
  SH215AF   908-912 
  SH216     913-913 
  SH217     914-915 
  SH218     916-916 
  SH219     917-917 
  SHCOL3B   918-919 
  SH223     920-921 
  SH225     922-923 
  SH226     924-925 
  SH227     926-930 
  SH227AA   931-935 
  SH227AB   936-940 
  SH227AC   941-945 
  SH227AD   946-950 
  SH227AE   951-955 
  SH227AF   956-960 
  SH227AG   961-965 
  SH228     966-966 
  SH229     967-968 
  SH230     969-970 
  SH231     971-975 
  SH231AA   976-980 
  SH231AB   981-985 
  SH231AC   986-990 
  SH231AD   991-995 
  SH231AE   996-1000
  SH231AF  1001-1005
  SH231AG  1006-1010
  SH232    1011-1011
  SH233    1012-1013
  SH234    1014-1015
  SH235    1016-1020
  SH235AA  1021-1025
  SH235AB  1026-1030
  SH235AC  1031-1035
  SH235AD  1036-1040
  SH235AE  1041-1045
  SH235AF  1046-1050
  SH235AG  1051-1055
  SH236    1056-1056
  SH237    1057-1058
  SH238    1059-1060
  SH239    1061-1061
  SH240    1062-1062
 .
VARIABLE LABELS
   HHID     "Case Identification"
  /HVIDX    "Line number"
  /HV000    "Country code and phase"
  /HV001    "Cluster number"
  /HV002    "Household number"
  /HV003    "Respondent's line number (answering Household questionnaire)"
  /HV004    "Ultimate area unit"
  /HV005    "Household sample weight (6 decimals)"
  /HV006    "Month of interview"
  /HV007    "Year of interview"
  /HV008    "Date of interview (CMC)"
  /HV009    "Number of household members"
  /HV010    "Number of eligible women in household"
  /HV011    "Number of eligible men in household"
  /HV012    "Number of de jure members"
  /HV013    "Number of de facto members"
  /HV014    "Number of children 5 and under (de jure)"
  /HV015    "Result of household interview"
  /HV016    "Day of interview"
  /HV017    "Number of visits"
  /HV018    "Interviewer identification"
  /HV019    "Keyer identification"
  /HV020    "Ever-married sample"
  /HV021    "Primary sampling unit"
  /HV022    "Sample strata for sampling errors"
  /HV023    "Stratification used in sample design"
  /HV024    "Province"
  /HV025    "Type of place of residence"
  /HV026    "Place of residence"
  /HV027    "Household selected for male interview"
  /HV028    "Household weight for male subsample (6 decimals)"
  /HV030    "Field supervisor"
  /HV031    "Field editor"
  /HV032    "Office editor"
  /HV035    "Number of eligible children for height and weight"
  /HV040    "Cluster altitude in meters"
  /HV041    "Total adults measured"
  /HV042    "Household selected for hemoglobin"
  /HV044    "Household selected for Domestic Violence module"
  /HV201    "Source of drinking water"
  /HV202    "NA - Source of non-drinking water"
  /HV204    "Time to get to water source (minutes)"
  /HV205    "Type of toilet facility"
  /HV206    "Has electricity"
  /HV207    "Has radio"
  /HV208    "Has television"
  /HV209    "Has refrigerator"
  /HV210    "Has bicycle"
  /HV211    "Has motorcycle/scooter"
  /HV212    "Has car/truck"
  /HV213    "Main floor material"
  /HV214    "Main wall material"
  /HV215    "Main roof material"
  /HV216    "Number of rooms used for sleeping"
  /HV217    "Relationship structure"
  /HV218    "Line number of head of household"
  /HV219    "Sex of head of household"
  /HV220    "Age of head of household"
  /HV221    "Has telephone (land-line)"
  /HV225    "Share toilet with other households"
  /HV226    "Type of cooking fuel"
  /HV227    "Has mosquito bed net for sleeping"
  /HV228    "Children under 5 slept under mosquito bed net last night"
  /HV230A   "Place where household members wash their hands"
  /HV230B   "Presence of water at hand washing place"
  /HV232    "Items present: Soap or detergent"
  /HV232B   "Items present: Ash, mud, sand"
  /HV232C   "NA - Items present: CS"
  /HV232D   "NA - Items present: CS"
  /HV232E   "NA - Items present: CS"
  /HV232Y   "Items present: None"
  /HV234    "NA - Result of salt test for iodine (PPM)"
  /HV234A   "Result of salt test for iodine"
  /HV235    "Location of source for water"
  /HV236    "NA - Person fetching water"
  /HV237    "Anything done to water to make safe to drink"
  /HV237A   "Water usually treated by: boil"
  /HV237B   "Water usually treated by: add bleach/chlorine"
  /HV237C   "Water usually treated by: strain through a cloth"
  /HV237D   "Water usually treated by: use water filter"
  /HV237E   "Water usually treated by: solar disinfection"
  /HV237F   "Water usually treated by: let it stand and settle"
  /HV237G   "NA - Water usually treated by: CS"
  /HV237H   "NA - Water usually treated by: CS"
  /HV237I   "NA - Water usually treated by: CS"
  /HV237J   "NA - Water usually treated by: CS"
  /HV237K   "NA - Water usually treated by: CS"
  /HV237X   "Water usually treated by: other"
  /HV237Z   "Water usually treated by: don't know"
  /HV238    "Number of households sharing toilet"
  /HV239    "NA - Food cooked on stove or open fire"
  /HV240    "NA - Household has a chimney, hood or neither"
  /HV241    "Food cooked in the house/ separate building/ outdoors"
  /HV242    "Household has separate room used as kitchen"
  /HV243A   "Has mobile telephone"
  /HV243B   "Has watch"
  /HV243C   "Has animal-drawn cart"
  /HV243D   "Has boat with a motor"
  /HV244    "Owns land usable for agriculture"
  /HV245    "Hectares of agricultural land (1 decimal)"
  /HV246    "Owns livestock, herds or farm animals"
  /HV246A   "NA - Owns cattle"
  /HV246B   "Owns cows/ bulls"
  /HV246C   "Owns horses/ donkeys/ mules"
  /HV246D   "Owns goats"
  /HV246E   "Owns sheep"
  /HV246F   "Owns chickens"
  /HV246G   "Pigs"
  /HV246H   "Duck"
  /HV246I   "NA - Owns CS"
  /HV246J   "NA - Owns CS"
  /HV246K   "NA - Owns CS"
  /HV247    "Has bank account"
  /HV252    "Frequency household members smoke inside the house"
  /HV253    "NA - Has dwelling been sprayed against mosquitoes in last 12 months"
  /HV253A   "NA - Dwelling sprayed by: government worker/program"
  /HV253B   "NA - Dwelling sprayed by: private company"
  /HV253C   "NA - Dwelling sprayed by: NGO"
  /HV253D   "NA - Dwelling sprayed by: CS"
  /HV253E   "NA - Dwelling sprayed by: CS"
  /HV253F   "NA - Dwelling sprayed by: CS"
  /HV253G   "NA - Dwelling sprayed by: CS"
  /HV253H   "NA - Dwelling sprayed by: CS"
  /HV253X   "NA - Dwelling sprayed by: other"
  /HV253Z   "NA - Dwelling sprayed by: don't know"
  /HV270    "Wealth index"
  /HV271    "Wealth index factor score (5 decimals)"
  /HML1     "Number of mosquito bed nets"
  /HML1A    "Number of mosquito bed nets with specific information"
  /HML2     "Number of children under mosquito bed net previous night"
  /CHL0     "NA - Number of de-jure children 5-14 for child labor module"
  /SHPOOL   "Pool"
  /SHNPROVIN "New Province"
  /SH110F   "Has generator"
  /SH110G   "Has stove/Cooker"
  /SH110H   "Has chair"
  /SH110I   "Has bed"
  /SH110J   "Has lights"
  /SH110K   "Has oven"
  /SH110L   "Has hoe"
  /SH110M   "Has sewing Machine"
  /SH118H   "Has a canoe with a motor"
  /SH118I   "Has computer"
  /SH118J   "Rent house"
  /SH136AA  "How can contract malaria : mosquito bite"
  /SH136AB  "How can contract malaria : bites other insects"
  /SH136AC  "How can contract malaria : blood transfusion"
  /SH136AD  "How can contract malaria : mother to child"
  /SH136AE  "How can contract malaria : drinking water"
  /SH136AF  "How can contract malaria : sorcery"
  /SH136AX  "How can contract malaria : other"
  /SH136AZ  "How can contract malaria : don't know"
  /SH136BA  "Principal symptom of malaria : fever"
  /SH136BB  "Principal symptom of malaria : headache"
  /SH136BC  "Principal symptom of malaria : generalized pain"
  /SH136BD  "Principal symptom of malaria : diarrhea"
  /SH136BE  "Principal symptom of malaria : coma"
  /SH136BF  "Principal symptom of malaria : shiver"
  /SH136BG  "Principal symptom of malaria : convulsions"
  /SH136BX  "Principal symptom of malaria : other"
  /SH136BZ  "Principal symptom of malaria : don't know"
  /SH136CA  "Best way to prevent malaria : nothing"
  /SH136CB  "Best way to prevent malaria : using insecticides"
  /SH136CC  "Best way to prevent malaria : using smoking stick"
  /SH136CD  "Best way to prevent malaria : fumigation with plant species"
  /SH136CE  "Best way to prevent malaria : using a mosquito net impregnated with insecticide"
  /SH136CF  "Best way to prevent malaria : using a simple mosquito net"
  /SH136CG  "Best way to prevent malaria : making sure surroundings are clean"
  /SH136CX  "Best way to prevent malaria : other"
  /SH242    "Total amount of money spent on health in last 4 weeks"
  /SH252A   "Rank of the child"
  /SH252B   "Child line number"
  /SH252C   "Child age"
  /SH256A   "Worked on plot / farm / food garden / looked after animals"
  /SH256B   "Helped in family / relative's business/ran own business"
  /SH256C   "Produced/sold articles/handicrafts/clothes/food or agricultural products"
  /SH256D   "Engaged in any other activity"
  /SH258    "Number of hours spent on these activities"
  /SH259    "Activities require carrying heavy loads"
  /SH260    "Activities require working with dangerous tools or operating heavy machinery"
  /SH261A   "Child exposed to dust, fumes or gas"
  /SH261B   "Child exposed to extreme cold, heat or humidity"
  /SH261C   "Child exposed to loud noise or vibration"
  /SH261D   "Child required to work at heights"
  /SH261E   "Child required to work with chemicals or explosives"
  /SH261F   "Child exposed to other things, processes or conditions bad for health or safety"
  /SH262    "Fetch water or collect firewood for household use"
  /SH263    "Number of hours spent on fetching water or collecting firewood for household use"
  /SH264A   "Shopping for household"
  /SH264B   "Repair household equipment"
  /SH264C   "Cooking / cleaning utensils /house"
  /SH264D   "Washing clothes"
  /SH264E   "Caring for children"
  /SH264F   "Caring for old / sick people"
  /SH264G   "Other household tasks"
  /SH266    "Number of hours in these activities"
  /SH271    "Child line number"
  /SH272A   "Revoke privileges to child"
  /SH272B   "Explained why behavior was wrong"
  /SH272C   "Shook child"
  /SH272D   "Yelled or screamed at child"
  /SH272E   "Gave child something else to do"
  /SH272F   "Hit child on the bottom with hands"
  /SH272G   "Hit child on the bottom or elsewhere with belt, brush, stick, etc."
  /SH272H   "Called child dumb, lazy or another name"
  /SH272I   "Hit or slapped child on the face, head or ears"
  /SH272J   "Hit or slapped child on the hand, arm or leg"
  /SH272K   "Beat child again and again, as strong as possible"
  /SH273    "Child needs to be physically punished to be brought up properly"
  /HV101    "Relationship to head"
  /HV102    "Usual resident"
  /HV103    "Slept last night"
  /HV104    "Sex of household member"
  /HV105    "Age of household members"
  /HV106    "Highest educational level attained"
  /HV107    "Highest year of education completed"
  /HV108    "Education completed in single years"
  /HV109    "Educational attainment"
  /HV110    "NA - Member still in school"
  /HV111    "Mother alive"
  /HV112    "Mother's line number"
  /HV113    "Father alive"
  /HV114    "Father's line number"
  /HV115    "Current marital status"
  /HV116    "Currently, formerly, never married"
  /HV117    "Eligibility for female interview"
  /HV118    "Eligibility for male interview"
  /HV120    "Children eligibility for height/weight and hemoglobin"
  /HV121    "Member attended school during current school year"
  /HV122    "Educational level during current school year"
  /HV123    "Grade of education during current school year"
  /HV124    "Education in single years - current school year"
  /HV125    "NA - Member attended school during previous school year"
  /HV126    "NA - Educational level during previous school year"
  /HV127    "NA - Grade of education during previous school year"
  /HV128    "NA - Education in single years - previous school year"
  /HV129    "NA - School attendance status"
  /HV140    "Member has a birth certificate"
  /IDXH4    "Index to Household Schedule"
  /SH21     "In last six month addmitted and stayed overnight in health facility"
  /SH22     "Eligible for in-patient module"
  /SH23     "In last 4 weeks received care without staying overnight"
  /SH24     "Eligible for out-patient module"
  /SH276    "Child line number in the Household"
  /SH277    "Child sex"
  /SH278    "Child age"
  /SH279    "Has any serious delay in sitting standing, or walking"
  /SH280    "Has difficulty seeing, either in the daytime or at night"
  /SH281    "Has any difficulty hearing (uses hearing aid, hears with difficulty or completely deaf)"
  /SH282    "Seems to understand what you are saying"
  /SH283    "Have difficulty in walking or moving his/her arms or does he/she have weakness and/or stiffness in the arms or legs"
  /SH284    "Sometimes have fits, become rigid, or lose consciousness"
  /SH285    "Learn to do things like other children his/her age"
  /SH286    "Speak at all (can he/she make him or herself understood in words; can he/she say any recognizable words)"
  /SH288    "Speech in any way different from normal"
  /SH289    "Name at least one object"
  /SH290    "Appear in any way mentally backward, dull or slow"
  /SH310A   "Read consent statement for vaccination"
  /SH312    "Bar code for blood sample for vaccination"
  /SH318A   "Child suffering any illnesses or symptoms: prostration"
  /SH318B   "Child suffering any illnesses or symptoms: loss of consciousness"
  /SH318C   "Child suffering any illnesses or symptoms: difficult breathing"
  /SH318D   "Child suffering any illnesses or symptoms: convulsions"
  /SH318E   "Child suffering any illnesses or symptoms: bleeding"
  /SH318F   "Child suffering any illnesses or symptoms:  jaundice"
  /SH318G   "Child suffering any illnesses or symptoms: dark urine"
  /SH318H   "Child suffering any illnesses or symptoms: vomiting"
  /SH318Y   "Child suffering any illnesses or symptoms: no symptoms"
  /SH322    "Taking cta to treat the malaria"
  /SH325    "Acceptance of medicine"
  /SH327    "Result code of malaria treatment and referral"
  /SHROUG   "Result of Vaccination test : measles"
  /SHOREI   "Result of Vaccination test : mumps"
  /SHRUBE   "Result of Vaccination test : rubella"
  /SHVARI   "Result of Vaccination test : chickenpox"
  /SHTETA   "Result of Vaccination test : tetanus"
  /HA0      "Index to Household Schedule"
  /HA1      "Woman's age in years"
  /HA2      "Woman's weight in kilograms (1 decimal)"
  /HA3      "Woman's height in centimeters (1 decimal)"
  /HA4      "Height/Age percentile"
  /HA5      "Height/Age standard deviation"
  /HA6      "Height/Age percent ref. median"
  /HA11     "Weight/Height standard deviation (DHS)"
  /HA12     "Weight/Height percent ref. median (DHS)"
  /HA12A    "Weight/Height percent ref. median (Fog)"
  /HA12B    "Weight/Height percent ref. median (WHO)"
  /HA13     "Result of measurement - height/weight"
  /HA32     "Date of birth (CMC)"
  /HA33     "Completeness of HA32 information"
  /HA35     "Smoking (cigarettes in last 24 hours)"
  /HA40     "Body Mass Index"
  /HA41     "Rohrer's index"
  /HA50     "Under age 18"
  /HA51     "Line number of parent/caretaker"
  /HA52     "Read consent statement - hemoglobin"
  /HA53     "Hemoglobin level (g/dl - 1 decimal)"
  /HA54     "Currently pregnant"
  /HA55     "Result of measurement - hemoglobin"
  /HA56     "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
  /HA57     "Anemia level"
  /HA58     "NA - Agrees to referral - anemia"
  /HA60     "Marital status"
  /HA61     "Read consent statement - HIV"
  /HA62     "Bar code for HIV blood sample"
  /HA63     "Result of measurement - HIV"
  /HA64     "Consent for additional tests"
  /HA65     "Result of woman's individual interview"
  /HA66     "Woman's highest educational level"
  /HA67     "Woman's highest year of education"
  /HA68     "Woman's highest educational level (for preliminary and final report)"
  /HA69     "HIV weight (6 decimals)"
  /HA70     "Interviewer that took blood for HIV testing"
  /HC0      "Index to Household Schedule"
  /HC1      "Child's age in months"
  /HC2      "Child's weight in kilograms (1 decimal)"
  /HC3      "Child's height in centimeters (1 decimal)"
  /HC4      "Height/Age percentile"
  /HC5      "Height/Age standard deviation"
  /HC6      "Height/Age percent of ref. median"
  /HC7      "Weight/Age percentile"
  /HC8      "Weight/Age standard deviation"
  /HC9      "Weight/Age percent of ref. median"
  /HC10     "Weight/Height percentile"
  /HC11     "Weight/Height standard deviation"
  /HC12     "Weight/Height percent of ref. median"
  /HC13     "Result of measurement - height/weight"
  /HC15     "Height: lying or standing"
  /HC16     "Day of birth"
  /HC17     "Date measured (day)"
  /HC18     "Date measured (month)"
  /HC19     "Date measured (year)"
  /HC27     "Sex"
  /HC30     "Month of birth"
  /HC31     "Year of birth"
  /HC32     "Date of birth (CMC)"
  /HC33     "Completeness of HC32 information"
  /HC51     "Line number of parent/caretaker"
  /HC52     "Read consent statement - hemoglobin"
  /HC53     "Hemoglobin level (g/dl - 1 decimal)"
  /HC55     "Result of measurement - hemoglobin"
  /HC56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
  /HC57     "Anemia level"
  /HC58     "NA - Agrees to referral - anemia"
  /HC60     "Mother's line number (woman's questionnaire)"
  /HC61     "Mother's highest educational level"
  /HC62     "Mother's highest year of education"
  /HC63     "Preceding birth interval (months)"
  /HC64     "Birth order number"
  /HC68     "Mother's highest educational level (for preliminary and final report)"
  /HC70     "Height/Age standard deviation (new WHO)"
  /HC71     "Weight/Age standard deviation (new WHO)"
  /HC72     "Weight/Height standard deviation (new WHO)"
  /HC73     "BMI standard deviation (new WHO)"
  /HB0      "Index to Household Schedule"
  /HB1      "Man's age in years"
  /HB2      "NA - Man's weight in kilograms (1 decimal)"
  /HB3      "NA - Man's height in centimeters (1 decimal)"
  /HB4      "NA - Height/Age percentile"
  /HB5      "Height/Age standard deviation"
  /HB6      "NA - Height/Age percent ref. median"
  /HB11     "Weight/Height standard deviation (DHS)"
  /HB12     "NA - Weight/Height percent ref. median (DHS)"
  /HB12A    "NA - Weight/Height percent ref. median (Fog)"
  /HB12B    "NA - Weight/Height percent ref. median (WHO)"
  /HB13     "NA - Result of measurement - height/weight"
  /HB32     "Date of birth (CMC)"
  /HB33     "Completeness of HB32 information"
  /HB35     "Smoking (cigarettes in last 24 hours)"
  /HB40     "NA - Body Mass Index"
  /HB41     "NA - Rohrer's index"
  /HB50     "Under age 18"
  /HB51     "Line number of parent/caretaker"
  /HB52     "Read consent statement - hemoglobin"
  /HB53     "Hemoglobin level (g/dl - 1 decimal)"
  /HB55     "Result of measurement - hemoglobin"
  /HB56     "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
  /HB57     "Anemia level"
  /HB58     "NA - Agrees to referral - anemia"
  /HB60     "Marital status"
  /HB61     "Read consent statement - HIV"
  /HB62     "Bar code for HIV blood sample"
  /HB63     "Result of measurement - HIV"
  /HB64     "Consent for additional tests"
  /HB65     "Result of man's individual interview"
  /HB66     "Man's highest educational level"
  /HB67     "Man's highest year of education"
  /HB68     "Man's highest educational level (for preliminary and final report)"
  /HB69     "HIV weight (6 decimals)"
  /HB70     "Interviewer that took blood for HIV testing"
  /HMLIDX   "Mosquito Bed Net Designation Number"
  /HML3     "Net observed by interviewer"
  /HML4     "Months ago net obtained"
  /HML5     "Net treated with insecticide when bought"
  /HML6     "Net treatment status"
  /HML7     "Brand of net"
  /HML8     "Net treated since receiving"
  /HML9     "Time since last re-treatment (months)"
  /HML10    "Insecticide-Treated Net (ITN)"
  /HML11    "Number of persons who slept under this net"
  /HML21    "Someone slept under this net last night"
  /HMLA     "Line number of person who slept in this net"
  /HMLB     "Line number of person who slept in this net"
  /HMLC     "Line number of person who slept in this net"
  /HMLD     "Line number of person who slept in this net"
  /HMLE     "NA - Line number of person who slept in this net"
  /HMHIDX   "Index to Household Schedule"
  /HML12    "Type of Mosquito Bed Net(s) person slept under last night"
  /HML13    "Net Designation Number (HMLIDX) for 1st net person slept under last night"
  /HML14    "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
  /HML15    "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
  /HML16    "Corrected age from Individual file"
  /HML16A   "Age in months (for children)"
  /HML17    "Flag for age from Individual file"
  /HML18    "Pregnancy status from Individual file"
  /HML19    "Person slept under an ever-treated net"
  /HML20    "Person slept under an LLIN net"
  /HML30    "Line number of parent/caretaker (for malaria testing)"
  /HML31    "Read consent statement for malaria"
  /HML32    "Final result of malaria from blood smear test"
  /HML32A   "NA - Presence of species: falciparum (Pf)"
  /HML32B   "NA - Presence of species: malariae (Pm)"
  /HML32C   "NA - Presence of species: ovale (Po)"
  /HML32D   "NA - Presence of species: vivax (Pv)"
  /HML32E   "NA - Presence of species: CS"
  /HML32F   "NA - Presence of species: CS"
  /HML32G   "NA - Presence of species: CS"
  /HML33    "Result of malaria measurement"
  /HML34    "Bar code for blood smear sample"
  /HML35    "Result of malaria rapid test"
  /SHCOL3A  "Column number - inpatient module"
  /SH203    "Line number of member"
  /SH205    "Where did patient hospitalized"
  /SH206    "Main reason for hospitalization"
  /SH207    "Total amount of money spent"
  /SH207AA  "Money spent - hospitalization"
  /SH207AB  "Money spent - drugs"
  /SH207AC  "Money spent - lab tests"
  /SH207AD  "Money spent - medical imaging/other tests"
  /SH207AE  "Money spent - transportation"
  /SH207AF  "Money spent - other"
  /SH208    "Stayed overnight at a facility another time in last six months"
  /SH209    "Where did patient hospitalized last time"
  /SH210    "Main reason for hospitalization"
  /SH211    "Total amount of money spent"
  /SH211AA  "Money spent - hospitalization"
  /SH211AB  "Money spent - drugs"
  /SH211AC  "Money spent - lab tests"
  /SH211AD  "Money spent - medical imaging/other tests"
  /SH211AE  "Money spent - transportation"
  /SH211AF  "Money spent - other"
  /SH212    "Stayed overnight at a facility another time in last six months"
  /SH213    "Where did patient hospitalized"
  /SH214    "Main reason for hospitalization"
  /SH215    "Total amount of money spent"
  /SH215AA  "Money spent - hospitalization"
  /SH215AB  "Money spent - drugs"
  /SH215AC  "Money spent - lab tests"
  /SH215AD  "Money spent - medical imaging/other tests"
  /SH215AE  "Money spent - transportation"
  /SH215AF  "Money spent - other"
  /SH216    "Besides three stays stayed overnight another time"
  /SH217    "Total times stayed overnight"
  /SH218    "Covered by health insurance"
  /SH219    "Type of insurance"
  /SHCOL3B  "Column number outpatient module"
  /SH223    "Line number of member"
  /SH225    "Type of health provider"
  /SH226    "Main reason to seek care"
  /SH227    "Total amount of money spent"
  /SH227AA  "Money spent - consultation fees"
  /SH227AB  "Money spent - drugs"
  /SH227AC  "Money spent - lab tests"
  /SH227AD  "Money spent - medical images"
  /SH227AE  "Money spent - medical goods"
  /SH227AF  "Money spent - transportation"
  /SH227AG  "Money spent - other"
  /SH228    "Got care another time in last four weeks"
  /SH229    "Where did patient stay"
  /SH230    "Main reason to seek care"
  /SH231    "Total amount of money spent"
  /SH231AA  "Money spent - consultation fees"
  /SH231AB  "Money spent - drugs"
  /SH231AC  "Money spent - lab tests"
  /SH231AD  "Money spent - medical images"
  /SH231AE  "Money spent - medical goods"
  /SH231AF  "Money spent - transportation"
  /SH231AG  "Money spent - other"
  /SH232    "Paid another visit seeking care"
  /SH233    "Where did patient stay"
  /SH234    "Main reason to seek care"
  /SH235    "Total amount of money spent"
  /SH235AA  "Money spent - consultation fees"
  /SH235AB  "Money spent - drugs"
  /SH235AC  "Money spent - lab tests"
  /SH235AD  "Money spent - medical images"
  /SH235AE  "Money spent - medical goods"
  /SH235AF  "Money spent - transportation"
  /SH235AG  "Money spent - other"
  /SH236    "Besides three visits another visit"
  /SH237    "Total number of outpatient visits"
  /SH238    "How many time money was spent ?"
  /SH239    "Covered by health insurance"
  /SH240    "Type of insurance"
 .
MISSING VALUE
   HV017    (9)
  /HV018    (999)
  /HV026    (9)
  /HV030    (999)
  /HV040    (9999)
  /HV201    (99)
  /HV202    (99)
  /HV204    (999)
  /HV205    (99)
  /HV206    (9)
  /HV207    (9)
  /HV208    (9)
  /HV209    (9)
  /HV210    (9)
  /HV211    (9)
  /HV212    (9)
  /HV213    (99)
  /HV214    (99)
  /HV215    (99)
  /HV216    (99)
  /HV219    (9)
  /HV220    (99)
  /HV221    (9)
  /HV225    (9)
  /HV226    (99)
  /HV227    (9)
  /HV228    (9)
  /HV230A   (9)
  /HV230B   (9)
  /HV232    (9)
  /HV232B   (9)
  /HV232C   (9)
  /HV232D   (9)
  /HV232E   (9)
  /HV232Y   (9)
  /HV234    (999)
  /HV234A   (9)
  /HV235    (9)
  /HV236    (9)
  /HV237    (9)
  /HV237A   (9)
  /HV237B   (9)
  /HV237C   (9)
  /HV237D   (9)
  /HV237E   (9)
  /HV237F   (9)
  /HV237G   (9)
  /HV237H   (9)
  /HV237I   (9)
  /HV237J   (9)
  /HV237K   (9)
  /HV237X   (9)
  /HV237Z   (9)
  /HV238    (99)
  /HV239    (9)
  /HV240    (9)
  /HV241    (9)
  /HV242    (9)
  /HV243A   (9)
  /HV243B   (9)
  /HV243C   (9)
  /HV243D   (9)
  /HV244    (9)
  /HV245    (999)
  /HV246    (9)
  /HV246A   (99)
  /HV246B   (99)
  /HV246C   (99)
  /HV246D   (99)
  /HV246E   (99)
  /HV246F   (99)
  /HV246G   (99)
  /HV246H   (99)
  /HV246I   (99)
  /HV246J   (99)
  /HV246K   (99)
  /HV247    (9)
  /HV252    (9)
  /HV253    (9)
  /HV253A   (9)
  /HV253B   (9)
  /HV253C   (9)
  /HV253D   (9)
  /HV253E   (9)
  /HV253F   (9)
  /HV253G   (9)
  /HV253H   (9)
  /HV253X   (9)
  /HV253Z   (9)
  /HML1     (99)
  /HML2     (99)
  /SH110F   (9)
  /SH110G   (9)
  /SH110H   (9)
  /SH110I   (9)
  /SH110J   (9)
  /SH110K   (9)
  /SH110L   (9)
  /SH110M   (9)
  /SH118H   (9)
  /SH118I   (9)
  /SH118J   (9)
  /SH136AA  (9)
  /SH136AB  (9)
  /SH136AC  (9)
  /SH136AD  (9)
  /SH136AE  (9)
  /SH136AF  (9)
  /SH136AX  (9)
  /SH136AZ  (9)
  /SH136BA  (9)
  /SH136BB  (9)
  /SH136BC  (9)
  /SH136BD  (9)
  /SH136BE  (9)
  /SH136BF  (9)
  /SH136BG  (9)
  /SH136BX  (9)
  /SH136BZ  (9)
  /SH136CA  (9)
  /SH136CB  (9)
  /SH136CC  (9)
  /SH136CD  (9)
  /SH136CE  (9)
  /SH136CF  (9)
  /SH136CG  (9)
  /SH136CX  (9)
  /SH242    (99999)
  /SH252A   (9)
  /SH256A   (9)
  /SH256B   (9)
  /SH256C   (9)
  /SH256D   (9)
  /SH258    (99)
  /SH259    (9)
  /SH260    (9)
  /SH261A   (9)
  /SH261B   (9)
  /SH261C   (9)
  /SH261D   (9)
  /SH261E   (9)
  /SH261F   (9)
  /SH262    (9)
  /SH263    (99)
  /SH264A   (9)
  /SH264B   (9)
  /SH264C   (9)
  /SH264D   (9)
  /SH264E   (9)
  /SH264F   (9)
  /SH264G   (9)
  /SH266    (99)
  /SH272A   (9)
  /SH272B   (9)
  /SH272C   (9)
  /SH272D   (9)
  /SH272E   (9)
  /SH272F   (9)
  /SH272G   (9)
  /SH272H   (9)
  /SH272I   (9)
  /SH272J   (9)
  /SH272K   (9)
  /SH273    (9)
  /HV101    (99)
  /HV102    (9)
  /HV103    (9)
  /HV104    (9)
  /HV105    (99)
  /HV106    (9)
  /HV107    (99)
  /HV108    (99)
  /HV109    (9)
  /HV110    (9)
  /HV111    (9)
  /HV112    (99)
  /HV113    (9)
  /HV114    (99)
  /HV115    (9)
  /HV116    (9)
  /HV121    (9)
  /HV122    (9)
  /HV123    (99)
  /HV124    (99)
  /HV125    (9)
  /HV126    (9)
  /HV127    (99)
  /HV128    (99)
  /HV129    (9)
  /HV140    (9)
  /SH21     (9)
  /SH23     (9)
  /SH277    (9)
  /SH278    (99)
  /SH279    (9)
  /SH280    (9)
  /SH281    (9)
  /SH282    (9)
  /SH283    (9)
  /SH284    (9)
  /SH285    (9)
  /SH286    (9)
  /SH288    (9)
  /SH289    (9)
  /SH290    (9)
  /SH310A   (9)
  /SH318A   (9)
  /SH318B   (9)
  /SH318C   (9)
  /SH318D   (9)
  /SH318E   (9)
  /SH318F   (9)
  /SH318G   (9)
  /SH318H   (9)
  /SH318Y   (9)
  /SH322    (9)
  /SH325    (9)
  /SH327    (9)
  /SHROUG   (9)
  /SHOREI   (9)
  /SHRUBE   (9)
  /SHVARI   (9)
  /SHTETA   (9)
  /HA2      (9999)
  /HA3      (9999)
  /HA4      (9999)
  /HA5      (9999)
  /HA6      (99999)
  /HA11     (9999)
  /HA12     (99999)
  /HA12A    (99999)
  /HA12B    (99999)
  /HA13     (9)
  /HA35     (99)
  /HA40     (9999)
  /HA41     (9999)
  /HA50     (9)
  /HA51     (99)
  /HA52     (9)
  /HA53     (999)
  /HA54     (9)
  /HA55     (9)
  /HA56     (999)
  /HA57     (9)
  /HA58     (9)
  /HA60     (9)
  /HA61     (9)
  /HA63     (9)
  /HA64     (9)
  /HA66     (9)
  /HA67     (99)
  /HA68     (9)
  /HA70     (999)
  /HC2      (9999)
  /HC3      (9999)
  /HC4      (9999)
  /HC5      (9999)
  /HC6      (99999)
  /HC7      (9999)
  /HC8      (9999)
  /HC9      (99999)
  /HC10     (9999)
  /HC11     (9999)
  /HC12     (99999)
  /HC13     (9)
  /HC15     (9)
  /HC16     (99)
  /HC27     (9)
  /HC30     (99)
  /HC31     (9999)
  /HC51     (99)
  /HC52     (9)
  /HC53     (999)
  /HC55     (9)
  /HC56     (999)
  /HC57     (9)
  /HC58     (9)
  /HC60     (999)
  /HC61     (9)
  /HC62     (99)
  /HC63     (999)
  /HC64     (99)
  /HC68     (9)
  /HC70     (9999)
  /HC71     (9999)
  /HC72     (9999)
  /HC73     (9999)
  /HB2      (9999)
  /HB3      (9999)
  /HB4      (9999)
  /HB5      (9999)
  /HB6      (99999)
  /HB11     (9999)
  /HB12     (99999)
  /HB12A    (99999)
  /HB12B    (99999)
  /HB13     (9)
  /HB35     (99)
  /HB40     (9999)
  /HB41     (9999)
  /HB50     (9)
  /HB51     (99)
  /HB52     (9)
  /HB53     (999)
  /HB55     (9)
  /HB56     (999)
  /HB57     (9)
  /HB58     (9)
  /HB60     (9)
  /HB61     (9)
  /HB63     (9)
  /HB64     (9)
  /HB66     (9)
  /HB67     (99)
  /HB68     (9)
  /HB70     (999)
  /HML3     (9)
  /HML4     (99)
  /HML5     (9)
  /HML6     (9)
  /HML7     (99)
  /HML8     (9)
  /HML9     (99)
  /HML10    (9)
  /HML11    (9)
  /HML21    (9)
  /HMLA     (99)
  /HMLB     (99)
  /HMLC     (99)
  /HML12    (9)
  /HML16    (99)
  /HML18    (9)
  /HML31    (9)
  /HML32    (9)
  /HML32A   (9)
  /HML32B   (9)
  /HML32C   (9)
  /HML32D   (9)
  /HML32E   (9)
  /HML32F   (9)
  /HML32G   (9)
  /HML33    (9)
  /HML35    (9)
  /SH205    (99)
  /SH206    (9)
  /SH207    (99999)
  /SH207AA  (99999)
  /SH207AB  (99999)
  /SH207AC  (99999)
  /SH207AD  (99999)
  /SH207AE  (99999)
  /SH207AF  (99999)
  /SH208    (9)
  /SH209    (99)
  /SH210    (9)
  /SH211    (99999)
  /SH211AA  (99999)
  /SH211AB  (99999)
  /SH211AC  (99999)
  /SH211AD  (99999)
  /SH211AE  (99999)
  /SH211AF  (99999)
  /SH212    (9)
  /SH213    (99)
  /SH214    (9)
  /SH215    (99999)
  /SH215AA  (99999)
  /SH215AB  (99999)
  /SH215AC  (99999)
  /SH215AD  (99999)
  /SH215AE  (99999)
  /SH215AF  (99999)
  /SH216    (9)
  /SH217    (99)
  /SH218    (9)
  /SH219    (9)
  /SH225    (99)
  /SH226    (99)
  /SH227    (99999)
  /SH227AA  (99999)
  /SH227AB  (99999)
  /SH227AC  (99999)
  /SH227AD  (99999)
  /SH227AE  (99999)
  /SH227AF  (99999)
  /SH227AG  (99999)
  /SH228    (9)
  /SH229    (99)
  /SH230    (99)
  /SH231    (99999)
  /SH231AA  (99999)
  /SH231AB  (99999)
  /SH231AC  (99999)
  /SH231AD  (99999)
  /SH231AE  (99999)
  /SH231AF  (99999)
  /SH231AG  (99999)
  /SH232    (9)
  /SH233    (99)
  /SH234    (99)
  /SH235    (99999)
  /SH235AA  (99999)
  /SH235AB  (99999)
  /SH235AC  (99999)
  /SH235AD  (99999)
  /SH235AE  (99999)
  /SH235AF  (99999)
  /SH235AG  (99999)
  /SH236    (9)
  /SH237    (99)
  /SH238    (99)
  /SH239    (9)
  /SH240    (9)
 .
VALUE LABELS
   HV003   
      0 "Incomplete household"
  /HV015   
      1 "Completed"
      2 "No Household member/no competent member at home"
      3 "Entire Household absent for extended period of time"
      4 "Postponed"
      5 "Refused"
      6 "Dwelling vacant or address not a dwelling"
      7 "Dwelling destroyed"
      8 "Dwelling not found"
      9 "Other"
  /HV020   
      0 "All woman sample"
      1 "Ever married sample"
  /HV024   
      1 "Kinshasa"
      2 "Bandundu"
      3 "Bas-Congo"
      4 "Equateur"
      5 "Kasai-Occidental"
      6 "Kasai-Oriental"
      7 "Katanga"
      8 "Maniema"
      9 "Nord-Kivu"
     10 "Orientale"
     11 "Sud-Kivu"
  /HV025   
      1 "Urban"
      2 "Rural"
  /HV026   
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
  /HV027   
      0 "Not selected"
      1 "Men's survey"
      2 "Husband's survey"
  /HV042   
      0 "Not selected"
      1 "Selected"
  /HV044   
      0 "Household not selected"
      1 "Household selected"
  /HV201   
     10 "PIPED WATER"
     11 "Piped into dwelling"
     12 "Piped to yard/plot"
     13 "Public tap/standpipe"
     14 "Piped from the neighbor"
     20 "TUBE WELL WATER"
     21 "Tube well or borehole"
     30 "DUG WELL (OPEN/PROTECTED)"
     31 "Protected well"
     32 "Unprotected well"
     40 "SURFACE WATER"
     41 "Protected spring"
     42 "Unprotected spring"
     43 "River/dam/lake/ponds/stream/canal/irrigation channel"
     51 "Rainwater"
     61 "Tanker truck"
     62 "Cart with small tank"
     71 "Bottled water"
     96 "Other"
  /HV202   
     10 "PIPED WATER"
     11 "Piped into dwelling"
     12 "Piped to yard/plot"
     13 "Public tap/standpipe"
     20 "TUBE WELL WATER"
     21 "Tube well or borehole"
     30 "DUG WELL (OPEN/PROTECTED)"
     31 "Protected well"
     32 "Unprotected well"
     40 "SURFACE WATER"
     41 "Protected spring"
     42 "Unprotected spring"
     43 "River/dam/lake/ponds/stream/canal/irrigation channel"
     51 "Rainwater"
     61 "Tanker truck"
     62 "Cart with small tank"
     71 "Bottled water"
     96 "Other"
  /HV204   
    996 "On premises"
    998 "Don't know"
  /HV205   
     10 "FLUSH TOILET"
     11 "Flush to piped sewer system"
     12 "Flush to septic tank"
     13 "Flush to pit latrine"
     14 "Flush to somewhere else"
     15 "Flush, don't know where"
     20 "PIT TOILET LATRINE"
     21 "Ventilated Improved Pit latrine (VIP)"
     22 "Pit latrine with slab"
     23 "Pit latrine without slab/open pit"
     30 "NO FACILITY"
     31 "No facility/bush/field"
     41 "Composting toilet"
     42 "Bucket toilet"
     43 "Hanging toilet/latrine"
     96 "Other"
  /HV206   
      0 "No"
      1 "Yes"
  /HV207   
      0 "No"
      1 "Yes"
  /HV208   
      0 "No"
      1 "Yes"
  /HV209   
      0 "No"
      1 "Yes"
  /HV210   
      0 "No"
      1 "Yes"
  /HV211   
      0 "No"
      1 "Yes"
  /HV212   
      0 "No"
      1 "Yes"
  /HV213   
     10 "NATURAL"
     11 "Earth/sand"
     12 "Dung"
     20 "RUDIMENTARY"
     21 "Wood planks"
     22 "Palm/bambou"
     30 "FINISHED"
     31 "Parquet or polished wood"
     32 "Vinyl or asphalt strips"
     33 "Ceramic tiles"
     34 "Cement"
     35 "Carpet"
     96 "OTHER"
  /HV214   
     10 "NATURAL"
     11 "No walls"
     12 "Cane/palm/trunks"
     13 "Dirt"
     20 "RUDIMENTARY"
     21 "Bamboo with mud"
     22 "Stone with mud"
     23 "Adobe not covered/Bamboo/Wood with mud"
     24 "Reused wood"
     25 "Canvas/Tent/Carton"
     26 "Wood"
     30 "FINISHED"
     31 "Cement"
     32 "Stone with lime/cement"
     33 "Bricks"
     34 "Cement blocks"
     35 "Adobe covered"
     36 "Wood planks/shingles"
     96 "OTHER"
  /HV215   
     10 "NATURAL"
     11 "No roof"
     12 "Thatch/palm leaf"
     13 "Lump of earth"
     20 "RUDIMENTARY"
     21 "Rustic mat"
     22 "Palm/Bamboo"
     23 "Wood planks"
     24 "Cardboard"
     30 "FINISHED"
     31 "Metal"
     32 "Wood"
     33 "Zinc/Cement fiber"
     34 "Tiles/slate"
     35 "Cement"
     36 "Shingles"
     96 "OTHER"
  /HV217   
      0 "No adults"
      1 "One adult"
      2 "Two adults, opposite sex"
      3 "Two adults, same sex"
      4 "Three+ related adults"
      5 "Unrelated adults"
  /HV219   
      1 "Male"
      2 "Female"
  /HV220   
     97 "97+"
     98 "Don't know"
  /HV221   
      0 "No"
      1 "Yes"
  /HV225   
      0 "No"
      1 "Yes"
  /HV226   
      1 "Electricity"
      2 "LPG"
      3 "Natural gas"
      4 "Biogas"
      5 "Kerosene"
      6 "Coal, lignite"
      7 "Charcoal"
      8 "Wood"
      9 "Straw/shrubs/grass"
     10 "Agricultural crop"
     11 "Animal dung"
     95 "No food cooked in house"
     96 "Other"
  /HV227   
      0 "No"
      1 "Yes"
  /HV228   
      0 "No"
      1 "All children"
      2 "Some children"
      3 "No net in household"
  /HV230A  
      1 "Observed"
      2 "Not observed: not in dwelling"
      3 "Not observed: no permission to see"
      4 "Not observed: other reason"
  /HV230B  
      0 "Water not available"
      1 "Water is available"
  /HV232   
      0 "No"
      1 "Yes"
  /HV232B  
      0 "No"
      1 "Yes"
  /HV232C  
      0 "No"
      1 "Yes"
  /HV232D  
      0 "No"
      1 "Yes"
  /HV232E  
      0 "No"
      1 "Yes"
  /HV232Y  
      0 "No"
      1 "Yes: no cleansing agent observed"
  /HV234   
      0 "0 PPM (no iodine)"
      7 "Below 15 PPM"
     15 "15 PPM and above"
     30 "30 PPM"
    994 "Salt not tested"
    995 "No salt in household"
  /HV234A  
      0 "No iodine"
      1 "Iodine present"
      3 "No salt in household"
      6 "Salt not tested"
  /HV235   
      1 "In own dwelling"
      2 "In own yard/plot"
      3 "Elsewhere"
  /HV236   
      1 "Adult woman"
      2 "Adult man"
      3 "Female child under 15 years old"
      4 "Male child under 15 years old"
      6 "Other"
  /HV237   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237D  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237E  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237F  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237G  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237H  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237I  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237J  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237K  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237X  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237Z  
      0 "No"
      1 "Yes: don't know what is done to water"
      8 "Don't know"
  /HV238   
     95 "10 or more households"
     98 "Don't know"
  /HV239   
      1 "Open fire"
      2 "Open stove"
      3 "Closed stove with chimney"
      6 "Other"
  /HV240   
      0 "Neither chimney or hood"
      1 "Chimney"
      2 "Hood"
  /HV241   
      1 "In the house"
      2 "In a separate building"
      3 "Outdoors"
      6 "Other"
  /HV242   
      0 "No"
      1 "Yes"
  /HV243A  
      0 "No"
      1 "Yes"
  /HV243B  
      0 "No"
      1 "Yes"
  /HV243C  
      0 "No"
      1 "Yes"
  /HV243D  
      0 "No"
      1 "Yes"
  /HV244   
      0 "No"
      1 "Yes"
  /HV245   
    950 "95 or more"
    998 "Unknown"
  /HV246   
      0 "No"
      1 "Yes"
  /HV246A  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246B  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246C  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246D  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246E  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246F  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246G  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246H  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246I  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246J  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246K  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV247   
      0 "No"
      1 "Yes"
  /HV252   
      0 "Never"
      1 "Daily"
      2 "Weekly"
      3 "Monthly"
      4 "Less than monthly"
  /HV253   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253D  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253E  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253F  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253G  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253H  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253X  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253Z  
      0 "No"
      1 "Yes: don't know who sprayed the dwelling"
      8 "Don't know if it was sprayed"
  /HV270   
      1 "Poorest"
      2 "Poorer"
      3 "Middle"
      4 "Richer"
      5 "Richest"
  /HML1    
     98 "Don't know"
  /SHPOOL  
      1 "BOMA"
      2 "MATADI"
      3 "KENGE"
      4 "BANDUNDU"
      5 "INONGO"
      6 "KIKWIT"
      7 "KASONGO-LUNDA"
      8 "MBANDAKA"
      9 "BUMBA"
     10 "GEMENA"
     11 "GBADOLITE"
     12 "BOENDE"
     13 "KISANGANI"
     14 "BUTA"
     15 "ISIRO"
     16 "BUNIA"
     17 "BENI"
     18 "GOMA"
     19 "KINDU"
     20 "KASONGO"
     21 "BUKAVU"
     22 "UVIRA"
     23 "LUBUMBASHI"
     24 "KAMINA"
     25 "KOLWEZI"
     26 "KALEMIE"
     27 "MBUJI-MAYI"
     28 "MWENE-DITU"
     29 "KABINDA"
     30 "LODJA"
     31 "KANANGA"
     32 "MWEKA"
     33 "TSHIKAPA"
     34 "KINSHASA"
  /SHNPROVIN
      1 "Kinshasa"
      2 "Kwango"
      3 "Kwilu"
      4 "Mai-Ndombe"
      5 "Kongo Central"
      6 "Equateur"
      7 "Mongala"
      8 "Nord-Ubangi"
      9 "Sud-Ubangi"
     10 "Tshuapa"
     11 "Kasai"
     12 "Kasai-Central"
     13 "Kasai-Oriental"
     14 "Lomami"
     15 "Sankuru"
     16 "Haut-Katanga"
     17 "Haut-Lomami"
     18 "Lualaba"
     19 "Tanganyka"
     20 "Maniema"
     21 "Nord-Kivu"
     22 "Bas-Uele"
     23 "Haut-Uele"
     24 "Ituri"
     25 "Tshopo"
     26 "Sud-Kivu"
  /SH110F  
      0 "No"
      1 "Yes"
  /SH110G  
      0 "No"
      1 "Yes"
  /SH110H  
      0 "No"
      1 "Yes"
  /SH110I  
      0 "No"
      1 "Yes"
  /SH110J  
      0 "No"
      1 "Yes"
  /SH110K  
      0 "No"
      1 "Yes"
  /SH110L  
      0 "No"
      1 "Yes"
  /SH110M  
      0 "No"
      1 "Yes"
  /SH118H  
      0 "No"
      1 "Yes"
  /SH118I  
      0 "No"
      1 "Yes"
  /SH118J  
      0 "No"
      1 "Yes"
  /SH136AA 
      0 "No"
      1 "Yes"
  /SH136AB 
      0 "No"
      1 "Yes"
  /SH136AC 
      0 "No"
      1 "Yes"
  /SH136AD 
      0 "No"
      1 "Yes"
  /SH136AE 
      0 "No"
      1 "Yes"
  /SH136AF 
      0 "No"
      1 "Yes"
  /SH136AX 
      0 "No"
      1 "Yes"
  /SH136AZ 
      0 "No"
      1 "Yes"
  /SH136BA 
      0 "No"
      1 "Yes"
  /SH136BB 
      0 "No"
      1 "Yes"
  /SH136BC 
      0 "No"
      1 "Yes"
  /SH136BD 
      0 "No"
      1 "Yes"
  /SH136BE 
      0 "No"
      1 "Yes"
  /SH136BF 
      0 "No"
      1 "Yes"
  /SH136BG 
      0 "No"
      1 "Yes"
  /SH136BX 
      0 "No"
      1 "Yes"
  /SH136BZ 
      0 "No"
      1 "Yes"
  /SH136CA 
      0 "No"
      1 "Yes"
  /SH136CB 
      0 "No"
      1 "Yes"
      8 "Dont Know"
  /SH136CC 
      0 "No"
      1 "Yes"
      8 "Dont Know"
  /SH136CD 
      0 "No"
      1 "Yes"
      8 "Dont Know"
  /SH136CE 
      0 "No"
      1 "Yes"
      8 "Dont Know"
  /SH136CF 
      0 "No"
      1 "Yes"
      8 "Dont Know"
  /SH136CG 
      0 "No"
      1 "Yes"
      8 "Dont Know"
  /SH136CX 
      0 "No"
      1 "Yes"
      8 "Dont Know"
  /SH242   
      0 "Nothing"
  99995 "In kind only"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH256A  
      0 "No"
      1 "Yes"
  /SH256B  
      0 "No"
      1 "Yes"
  /SH256C  
      0 "No"
      1 "Yes"
  /SH256D  
      0 "No"
      1 "Yes"
  /SH258   
      0 "Less than 1 hour"
     96 "More than 96"
     98 "Don't know"
  /SH259   
      0 "No"
      1 "Yes"
  /SH260   
      0 "No"
      1 "Yes"
  /SH261A  
      0 "No"
      1 "Yes"
  /SH261B  
      0 "No"
      1 "Yes"
  /SH261C  
      0 "No"
      1 "Yes"
  /SH261D  
      0 "No"
      1 "Yes"
  /SH261E  
      0 "No"
      1 "Yes"
  /SH261F  
      0 "No"
      1 "Yes"
  /SH262   
      0 "No"
      1 "Yes"
  /SH263   
      0 "Less than 1 hour"
     96 "More than 96"
     98 "Don't know"
  /SH264A  
      0 "No"
      1 "Yes"
  /SH264B  
      0 "No"
      1 "Yes"
  /SH264C  
      0 "No"
      1 "Yes"
  /SH264D  
      0 "No"
      1 "Yes"
  /SH264E  
      0 "No"
      1 "Yes"
  /SH264F  
      0 "No"
      1 "Yes"
  /SH264G  
      0 "No"
      1 "Yes"
  /SH266   
      0 "Less than 1 hour"
     96 "More than 96"
     98 "Don't know"
  /SH272A  
      0 "No"
      1 "Yes"
  /SH272B  
      0 "No"
      1 "Yes"
  /SH272C  
      0 "No"
      1 "Yes"
  /SH272D  
      0 "No"
      1 "Yes"
  /SH272E  
      0 "No"
      1 "Yes"
  /SH272F  
      0 "No"
      1 "Yes"
  /SH272G  
      0 "No"
      1 "Yes"
  /SH272H  
      0 "No"
      1 "Yes"
  /SH272I  
      0 "No"
      1 "Yes"
  /SH272J  
      0 "No"
      1 "Yes"
  /SH272K  
      0 "No"
      1 "Yes"
  /SH273   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV101   
      1 "Head"
      2 "Wife or husband"
      3 "Son/daughter"
      4 "Son/daughter-in-law"
      5 "Grandchild"
      6 "Parent"
      7 "Parent-in-law"
      8 "Brother/sister"
      9 "Co-spouse"
     10 "Other relative"
     11 "Adopted/foster child"
     12 "Not related"
     13 "Niece/nephew by blood"
     14 "Niece/nephew by marriage"
     98 "Don't know"
  /HV102   
      0 "No"
      1 "Yes"
  /HV103   
      0 "No"
      1 "Yes"
  /HV104   
      1 "Male"
      2 "Female"
  /HV105   
     97 "97+"
     98 "Don't know"
  /HV106   
      0 "No education, preschool"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HV107   
     98 "Don't know"
  /HV108   
     97 "Inconsistent"
     98 "Don't know"
  /HV109   
      0 "No education"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Incomplete secondary"
      4 "Complete secondary"
      5 "Higher"
      8 "Don't know"
  /HV110   
      0 "No"
      1 "Yes"
  /HV111   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV112   
      0 "Mother not in household"
  /HV113   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV114   
      0 "Father not in household"
  /HV115   
      0 "Never married"
      1 "Married"
      2 "Living together"
      3 "Widowed"
      4 "Divorced/Not living together"
      5 "Not living together"
  /HV116   
      0 "Never married"
      1 "Currently married"
      2 "Formerly/ever married"
  /HV117   
      0 "Not eligible"
      1 "Eligible"
  /HV118   
      0 "Not eligible"
      1 "Eligible"
  /HV120   
      0 "Not eligible"
      1 "Eligible"
  /HV121   
      0 "No"
      1 "Currently attending"
      2 "Attended at some time"
  /HV122   
      0 "No education, preschool"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HV123   
     98 "Don't know"
  /HV124   
     97 "Inconsistent"
     98 "Don't know"
  /HV125   
      0 "No"
      1 "Yes"
  /HV126   
      0 "No education, preschool"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HV127   
     98 "Don't know"
  /HV128   
     97 "Inconsistent"
     98 "Don't know"
  /HV129   
      0 "Never attended"
      1 "Entered school"
      2 "Advanced"
      3 "Repeating"
      4 "Dropout"
      5 "Left school 2+ years ago"
      8 "Don't know"
  /HV140   
      0 "Neither certificate or registered"
      1 "Has certificate"
      2 "Registered"
      8 "Don't know"
  /SH21    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /SH22    
      0 "Not eligible"
  /SH23    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /SH24    
      0 "Not eligible"
  /SH277   
      1 "Male"
      2 "Female"
  /SH279   
      0 "No"
      1 "Yes"
  /SH280   
      0 "No"
      1 "Yes"
  /SH281   
      0 "No"
      1 "Yes"
  /SH282   
      0 "No"
      1 "Yes"
  /SH283   
      0 "No"
      1 "Yes"
  /SH284   
      0 "No"
      1 "Yes"
  /SH285   
      0 "No"
      1 "Yes"
  /SH286   
      0 "No"
      1 "Yes"
  /SH288   
      0 "No"
      1 "Yes"
  /SH289   
      0 "No"
      1 "Yes"
  /SH290   
      0 "No"
      1 "Yes"
  /SH310A  
      1 "Granted"
      2 "Refused"
  /SH312   
 99993 "Sample damaged/insufficient/not found in lab"
 99994 "Not present"
 99995 "Refused"
 99996 "Other"
 '?    ' "Missing"
  /SH318A  
      0 "No"
      1 "Yes"
  /SH318B  
      0 "No"
      1 "Yes"
  /SH318C  
      0 "No"
      1 "Yes"
  /SH318D  
      0 "No"
      1 "Yes"
  /SH318E  
      0 "No"
      1 "Yes"
  /SH318F  
      0 "No"
      1 "Yes"
  /SH318G  
      0 "No"
      1 "Yes"
  /SH318H  
      0 "No"
      1 "Yes"
  /SH318Y  
      0 "No"
      1 "Yes, no symptoms"
  /SH322   
      1 "Yes, CTA"
      2 "Yes, other CTA"
      3 "Yes, other"
      4 "No"
  /SH325   
      1 "Accepted medicine"
      2 "Refused"
      6 "Other"
  /SH327   
      1 "Medication given"
      2 "Meds refused"
      3 "Severe malaria referral"
      4 "Already taking meds referral"
      6 "Other"
  /SHROUG  
      0 "Negative"
      1 "Positive"
      3 "Test undetermined"
      4 "Not present"
      5 "Refused"
      6 "Others"
      8 "Sample not found in lab database"
  /SHOREI  
      0 "Negative"
      1 "Positive"
      3 "Test undetermined"
      4 "Not present"
      5 "Refused"
      6 "Others"
      8 "Sample not found in lab database"
  /SHRUBE  
      0 "Negative"
      1 "Positive"
      3 "Test undetermined"
      4 "Not present"
      5 "Refused"
      6 "Others"
      8 "Sample not found in lab database"
  /SHVARI  
      0 "Negative"
      1 "Positive"
      3 "Test undetermined"
      4 "Not present"
      5 "Refused"
      6 "Others"
      8 "Sample not found in lab database"
  /SHTETA  
      0 "Negative"
      1 "Positive"
      3 "Test undetermined"
      4 "Not present"
      5 "Refused"
      6 "Others"
      8 "Sample not found in lab database"
  /HA2     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HA3     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HA4     
   9998 "Flagged cases"
  /HA5     
   9998 "Flagged cases"
  /HA6     
  99998 "Flagged cases"
  /HA11    
   9998 "Flagged cases"
  /HA12    
  99998 "Flagged cases"
  /HA12A   
  99998 "Flagged cases"
  /HA12B   
  99998 "Flagged cases"
  /HA13    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HA33    
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      4 "Year and age - year ignored"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /HA35    
      0 "Doesn't smoke"
     80 "80+"
     94 "Smokes pipes, cigars, etc"
  /HA40    
   9998 "Flagged cases"
  /HA41    
   9998 "Flagged cases"
  /HA50    
      1 "Under age 18"
      2 "Age 18 or older"
  /HA51    
      0 "Not in household"
  /HA52    
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
  /HA53    
    994 "Not present"
    995 "Refused"
    996 "Other"
  /HA54    
      0 "No/don't know"
      1 "Yes"
  /HA55    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HA56    
    997 "Inconsistent"
  /HA57    
      1 "Severe"
      2 "Moderate"
      3 "Mild"
      4 "Not anemic"
  /HA58    
      0 "No"
      1 "Yes"
  /HA60    
      1 "Never in union"
      2 "Other"
  /HA61    
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
      4 "Sample not tested/lost/not enough DBS"
  /HA62    
 99992 "Woman's interview incomplete or woman is not de-facto"
 99993 "Sample damaged/insufficient/not found in lab"
 99994 "Not present"
 99995 "Refused"
 99996 "Other"
 '?    ' "Missing"
  /HA63    
      1 "Blood taken"
      2 "Not present"
      3 "Refused"
      4 "Sample not tested/lost/damaged/insufficient"
      5 "Not enough DBS to complete protocol"
      6 "Other"
  /HA64    
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
  /HA65    
      1 "Completed"
      2 "Not at home"
      3 "Postponed"
      4 "Refused"
      5 "Partly completed"
      6 "Incapacitated"
      7 "Other"
  /HA66    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HA67    
     98 "Don't know"
  /HA68    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HC2     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HC3     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HC4     
   9998 "Flagged cases"
  /HC5     
   9998 "Flagged cases"
  /HC6     
  99998 "Flagged cases"
  /HC7     
   9998 "Flagged cases"
  /HC8     
   9998 "Flagged cases"
  /HC9     
  99998 "Flagged cases"
  /HC10    
   9998 "Flagged cases"
  /HC11    
   9998 "Flagged cases"
  /HC12    
  99998 "Flagged cases"
  /HC13    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HC15    
      0 "Not measured"
      1 "Lying"
      2 "Standing"
  /HC16    
     97 "Inconsistent"
     98 "Don't know"
  /HC27    
      1 "Male"
      2 "Female"
  /HC30    
     97 "Inconsistent"
     98 "Don't know"
  /HC31    
   9997 "Inconsistent"
   9998 "Don't know"
  /HC33    
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /HC51    
      0 "Not in household"
  /HC52    
      1 "Granted"
      2 "Refused"
  /HC53    
    992 "Not present"
    993 "Refused"
    996 "Other"
  /HC55    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HC56    
    997 "Inconsistent"
  /HC57    
      1 "Severe"
      2 "Moderate"
      3 "Mild"
      4 "Not anemic"
  /HC58    
      0 "No"
      1 "Yes"
  /HC60    
    993 "Mother not de facto"
    994 "Incomplete woman's interview"
    995 "Not in household"
  /HC61    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HC62    
     98 "Don't know"
  /HC68    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HC70    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HC71    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HC72    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HC73    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HB2     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HB3     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HB4     
   9998 "Flagged cases"
  /HB5     
   9998 "Flagged cases"
  /HB6     
  99998 "Flagged cases"
  /HB11    
   9998 "Flagged cases"
  /HB12    
  99998 "Flagged cases"
  /HB12A   
  99998 "Flagged cases"
  /HB12B   
  99998 "Flagged cases"
  /HB13    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HB33    
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      4 "Year and age - year ignored"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /HB35    
      0 "Doesn't smoke"
     80 "80+"
     94 "Smokes pipes, cigars, etc"
  /HB40    
   9998 "Flagged cases"
  /HB41    
   9998 "Flagged cases"
  /HB50    
      1 "Under age 18"
      2 "Age 18 or older"
  /HB51    
      0 "Not in household"
  /HB52    
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
  /HB53    
    994 "Not present"
    995 "Refused"
    996 "Other"
  /HB55    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HB56    
    997 "Inconsistent"
  /HB57    
      1 "Severe"
      2 "Moderate"
      3 "Mild"
      4 "Not anemic"
  /HB58    
      0 "No"
      1 "Yes"
  /HB60    
      1 "Never in union"
      2 "Other"
  /HB61    
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
      4 "Sample not tested/lost/not enough DBS"
  /HB62    
 99992 "Man's interview incomplete or man is not de-facto"
 99993 "Sample damaged/insufficient/not found in lab"
 99994 "Not present"
 99995 "Refused"
 99996 "Other"
 '?    ' "Missing"
  /HB63    
      1 "Blood taken"
      2 "Not present"
      3 "Refused"
      4 "Sample not tested/lost/damaged/insufficient"
      5 "Not enough DBS to complete protocol"
      6 "Other"
  /HB64    
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
  /HB65    
      1 "Completed"
      2 "Not at home"
      3 "Postponed"
      4 "Refused"
      5 "Partly completed"
      6 "Incapacitated"
      7 "Other"
  /HB66    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HB67    
     98 "Don't know"
  /HB68    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HML3    
      0 "Not seen"
      1 "Yes, seen"
  /HML4    
     96 "More than 3 years ago"
     98 "Don't know"
  /HML5    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HML6    
      0 "Not pretreated"
      1 "Pretreated, permanent treatment"
      2 "Pretreated, requiring future treatment"
      3 "Not pretreated, came with kit and treated at home"
      4 "Pretreated, treatment type not known"
      6 "Other"
      8 "Don't know"
  /HML7    
     11 "Permanet 2.0"
     12 "Olyset"
     13 "Duranet"
     14 "Interceptor brand"
     15 "Yorkool LN brand"
     16 "Lifenet"
     17 "Magnet"
     18 "Serena"
     19 "Netprotect"
     21 "Other/Don't know brand (pretreated)"
     96 "Other brand"
     98 "Don't know brand"
  /HML8    
      0 "No"
      1 "Yes"
      2 "Permanent net"
      8 "Not sure"
  /HML9    
     95 "25+ months ago"
     96 "More than 3 years ago"
     98 "Don't know"
  /HML10   
      0 "No, don't know"
      1 "Yes"
  /HML11   
      5 "5+"
  /HML21   
      0 "No"
      1 "Yes"
      8 "Not sure (DK)"
  /HMLA    
      0 "No one"
  /HML12   
      0 "Did not sleep under a net"
      1 "Only treated (ITN) nets"
      2 "Both treated (ITN) and untreated nets"
      3 "Only untreated nets"
  /HML13   
      0 "Did not sleep under net"
  /HML16   
     97 "97+"
     98 "Don't know"
  /HML17   
      0 "No data from Individual file"
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      4 "Year and age - year ignored"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /HML18   
      0 "Not pregnant, don't know"
      1 "Pregnant"
  /HML19   
      0 "No"
      1 "Yes"
  /HML20   
      0 "No"
      1 "Yes"
  /HML30   
      0 "Not in household"
  /HML31   
      1 "Granted"
      2 "Refused"
  /HML32   
      0 "Negative"
      1 "Positive"
      3 "Unreadable"
      4 "Not present"
      5 "Refused"
      6 "Others"
      7 "Test undetermined"
      8 "Sample not found in lab database"
  /HML32A  
      0 "No"
      1 "Yes"
  /HML32B  
      0 "No"
      1 "Yes"
  /HML32C  
      0 "No"
      1 "Yes"
  /HML32D  
      0 "No"
      1 "Yes"
  /HML32E  
      0 "No"
      1 "Yes"
  /HML32F  
      0 "No"
      1 "Yes"
  /HML32G  
      0 "No"
      1 "Yes"
  /HML33   
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HML34   
 99993 "Sample damaged/insufficient/not found in lab"
 99994 "Not present"
 99995 "Refused"
 99996 "Other"
 '?    ' "Missing"
  /HML35   
      0 "Negative"
      1 "Positive"
  /SH205   
     11 "Hospital"
     12 "Health center"
     13 "Health post"
     14 "Maternity"
     16 "Other public"
     21 "Private hospital/Clinic"
     22 "Pharmacy"
     23 "Medical Office"
     24 "Mobile nurse"
     26 "Other private"
     96 "Other"
  /SH206   
      1 "Antenatal/Postnatal care"
      2 "Delivery"
      3 "Fever/malaria"
      4 "Other diseases than Fever/malaria"
      5 "Accident/injury"
      6 "Other"
  /SH207   
      0 "Nothing"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH207AA 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH207AB 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH207AC 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH207AD 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH207AE 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH207AF 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH208   
      0 "No"
      1 "Yes"
  /SH209   
     11 "Hospital"
     12 "Health center"
     13 "Health post"
     14 "Maternity"
     16 "Other public"
     21 "Private hospital/Clinic"
     22 "Pharmacy"
     23 "Medical Office"
     24 "Mobile nurse"
     26 "Other private"
     96 "Other"
  /SH210   
      1 "Antenatal/Postnatal care"
      2 "Delivery"
      3 "Fever/malaria"
      4 "Other diseases than Fever/malaria"
      5 "Accident/injury"
      6 "Other"
  /SH211   
      0 "Nothing"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH211AA 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH211AB 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH211AC 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH211AD 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH211AE 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH211AF 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH212   
      0 "No"
      1 "Yes"
  /SH213   
     11 "Hospital"
     12 "Health center"
     13 "Health post"
     14 "Maternity"
     16 "Other public"
     21 "Private hospital/Clinic"
     22 "Pharmacy"
     23 "Medical Office"
     24 "Mobile nurse"
     26 "Other private"
     96 "Other"
  /SH214   
      1 "Antenatal/Postnatal care"
      2 "Delivery"
      3 "Fever/malaria"
      4 "Other diseases than Fever/malaria"
      5 "Accident/injury"
      6 "Other"
  /SH215   
      0 "Free"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH215AA 
      0 "Free"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH215AB 
      0 "Free"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH215AC 
      0 "Free"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH215AD 
      0 "Free"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH215AE 
      0 "Free"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH215AF 
      0 "Free"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH216   
      0 "No"
      1 "Yes"
  /SH218   
      0 "No"
      1 "Yes"
  /SH219   
      1 "Mutual Insurance / Insurance community"
      2 "Health insurance by the employer"
      3 "Social Security"
      4 "Other private insurance commercial"
      6 "Other"
      8 "Don't know"
  /SH225   
     11 "Hospital"
     12 "Health center"
     13 "Health post"
     14 "Maternity"
     15 "Mobile clinic"
     16 "Mobile nurse"
     17 "Other public"
     21 "Private hospital/Clinic"
     22 "Pharmacy"
     23 "Private doctor"
     24 "Mobile clinic"
     25 "Medical Office"
     26 "Mobile private nurse"
     27 "Other private"
     31 "Shop"
     32 "Traditional practitioner"
     33 "Mobile vendor"
     96 "Other"
  /SH226   
      1 "Family planning"
      2 "Antenatal/Postnatal care"
      3 "Child health regular check-up"
      4 "Malaria"
      5 "Fever"
      6 "Diarrhea"
      7 "HIV/AIDS"
      8 "Other diseases"
      9 "Regular check-up/Preventive care"
     10 "Accident/injury"
     96 "Other"
     98 "Don't know"
  /SH227   
      0 "Nothing"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH227AA 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH227AB 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH227AC 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH227AD 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH227AE 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH227AF 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH227AG 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH228   
      0 "No"
      1 "Yes"
  /SH229   
     11 "Hospital"
     12 "Health center"
     13 "Health post"
     14 "Maternity"
     15 "Mobile clinic"
     16 "Mobile nurse"
     17 "Other public"
     21 "Private hospital/Clinic"
     22 "Pharmacy"
     23 "Private doctor"
     24 "Mobile clinic"
     25 "Medical Office"
     26 "Mobile private nurse"
     27 "Other private"
     31 "Shop"
     32 "Traditional practitioner"
     33 "Mobile vendor"
     96 "Other"
  /SH230   
      1 "Family planning"
      2 "Antenatal/Postnatal care"
      3 "Child health regular check-up"
      4 "Malaria"
      5 "Fever"
      6 "Diarrhea"
      7 "HIV/AIDS"
      8 "Other diseases"
      9 "Regular check-up/Preventive care"
     10 "Accident/injury"
     96 "Other"
  /SH231   
      0 "Nothing"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH231AA 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH231AB 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH231AC 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH231AD 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH231AE 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH231AF 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH231AG 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH232   
      0 "No"
      1 "Yes"
  /SH233   
     11 "Hospital"
     12 "Health center"
     13 "Health post"
     14 "Maternity"
     15 "Mobile clinic"
     16 "Mobile nurse"
     17 "Other public"
     21 "Private hospital/Clinic"
     22 "Pharmacy"
     23 "Private doctor"
     24 "Mobile clinic"
     25 "Medical Office"
     26 "Mobile private nurse"
     27 "Other private"
     31 "Shop"
     32 "Traditional practitioner"
     33 "Mobile vendor"
     96 "Other"
  /SH234   
      1 "Family planning"
      2 "Antenatal/Postnatal care"
      3 "Child health regular check-up"
      4 "Malaria"
      5 "Fever"
      6 "Diarrhea"
      7 "HIV/AIDS"
      8 "Other diseases"
      9 "Regular check-up/Preventive care"
     10 "Accident/injury"
     96 "Other"
  /SH235   
      0 "Nothing"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH235AA 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH235AB 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH235AC 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH235AD 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH235AE 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH235AF 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH235AG 
      0 "Nothing"
  99992 "Item not applicable"
  99995 "In kind"
  99996 "Less than 1$"
  99998 "Don't know"
  /SH236   
      0 "No"
      1 "Yes"
  /SH237   
     98 "Don't know"
  /SH238   
     98 "Don't know"
  /SH239   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /SH240   
      1 "Mutual Insurance / Insurance community"
      2 "Health insurance by the employer"
      3 "Social Security"
      4 "Other private insurance commercial"
      6 "Other"
      8 "Don't know"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\CD61\CDPR61FL.sav'.
